[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = "0.32.1"
anyhow = "1.0.100"
dotenvy = "0.15.7"
serde_json = "1.0.145"
solana-client = "3.0.10"
solana-sdk = "3.0.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }