cargo-features = ["edition2024"]

[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = "0.32.1"
anyhow = "1.0.100"
dotenvy = "0.15.7"
serde_json = "1.0.145"
solana-client = "3.0.10"
solana-sdk = "3.0.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
actix-web = "4"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls"] }
uuid = { version = "1", features = ["v4"] }
once_cell = "1.19"
axum = "0.8.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
chrono = "0.4"
# Encryption (for ephemeral key secure storage)
ring = "0.17"
ed25519-dalek = "1.0.1"